version: "3.4"
services:
  redis:
    image: redis:3.2
  db:
    restart: always
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
  web:
    restart: always
    labels:
      - "neos"
    volumes:
      - /data/www-provisioned/Web/_Resources
    image: ghcr.io/psmb/kateheodistr:master
    hostname: 'kateheo'
    networks:
      - default
      - main
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"
        - "traefik.docker.network=main"
        - "traefik.frontend.rule=Host:kateheo.ru,www.kateheo.ru,dev.kateheo.ru"
    ports:
      - '80'
      - '1123:22'
    depends_on:
      - db
      - redis
    environment:
      IMPORT_GITHUB_PUB_KEYS: 'dimaip,zaveryukha'
volumes:
  db-data:
networks:
  main:
    external:
      name: main
