redis:
  image: redis:3.2
db:
  image: mariadb:10.3
  restart: always
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: admin
    MYSQL_PASSWORD: pass
web:
  image: dimaip/kateheodistr:latest
  ports:
    - '80'
    - '1123:22'
  links:
    - db:db
    - redis:redis
  volumes:
    - /data
    - ./Persistent:/data/shared/Data/Persistent
    - /etc/localtime:/etc/localtime:ro
  environment:
    - PHP_TIMEZONE=Europe/Moscow
    - VIRTUAL_HOST=kateheo.ru,www.kateheo.ru,dev.kateheo.ru,next.kateheo.ru
    - REPOSITORY_URL=https://github.com/psmb/KateheoDistr
    - LETSENCRYPT_HOST=kateheo.ru,www.kateheo.ru
    - LETSENCRYPT_EMAIL=dimaip@gmail.com
    - IMPORT_GITHUB_PUB_KEYS=dimaip,zaveryukha
    - AWS_ENDPOINT=https://hb.bizmrg.com
    - AWS_BACKUP_ARN=s3://psmb-neos-resources/db/kateheo/
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  
