dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /var/lib/mysql

redis:
  image: redis

db:
  image: million12/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: pass

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - data:/data
#    - Persistent:/data/www/kateheo.loc/surf/shared/Data/Persistent
    - /etc/localtime:/etc/localtime:ro

web:
  image: dimaip/kateheodistr:latest
  ports:
    - '80'
  links:
    - db:db
    - redis
  volumes_from:
    - webdata
  environment:
    VIRTUAL_HOST: 'kateheo.loc,dev.kateheo.loc,next.kateheo.loc'
    T3APP_NAME: 'kateheo.loc'

ssh:
  image: million12/php-app-ssh
  ports:
    - '22'
  links:
    - db:db
    - redis
    - web:web
  volumes_from:
    - webdata
  environment:
    IMPORT_GITHUB_PUB_KEYS: dimaip

